# Start from the official PHP 8.1 FPM Alpine image
FROM php:8.1-fpm-alpine


################################################
RUN apk update && apk upgrade

# Install dependencies
RUN apk add --no-cache \
    unzip nginx supervisor php-intl nano bash \
    zip libpq-dev libpng-dev libwebp-dev php-zip libzip-dev

# Install necessary PHP extensions
RUN docker-php-ext-install pdo  pdo_pgsql  pgsql  pcntl exif  pdo_mysql opcache sockets zip

# Set recommended PHP configurations
RUN echo "opcache.enable_cli=1" >> /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini && \
    echo "memory_limit=-1" >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini

################################################

# Create directories for Nginx and supervisor
RUN mkdir -p /run/nginx && \
    mkdir -p /var/log/supervisor


# Set up Nginx
COPY confs/nginx.conf /etc/nginx/nginx.conf
COPY confs/default.conf /etc/nginx/conf.d/default.conf

# Set up Supervisor
COPY confs/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

################################################

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

################################################

# Set up the working directory
WORKDIR /var/www/html

# Expose ports for Nginx
EXPOSE 80
EXPOSE 443

################################################

# Start supervisord to manage Nginx and PHP-FPM processes
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]