FROM node:14.17.5

# Install nginx
#RUN apt-get update && apt-get install nginx

# Install Angular CLI and dependencies
RUN npm install -g npm@6.14.14 @angular/cli@12.2.18

# Configure nginx
COPY confs/nginx.conf /etc/nginx/nginx.conf
COPY confs/default.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
